import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, CheckSquare, ChevronLeft, ChevronRight, Search, Trash2, X } from "lucide-react";
import { useLocation } from "react-router-dom";
import { useAuth } from "../../auth/AuthProvider";
import {
  executeLabourDataCleanup, fetchLabourSettlementHistory, fetchLegacyLabourEarnings, previewLabourDataCleanup,
  resolveLabourCleanupSelection, type LabourCleanupPreview, type LabourCleanupTarget, type LabourReconciliationFilters,
  type LabourReconciliationSummary, type LabourSettlementHistoryRecord, type LegacyLabourEarningRecord,
} from "../../lib/api";
import { formatMoney } from "../../lib/format";
import { getActiveFarmId, getActiveSeasonId, offlineDb } from "../../lib/offline-db";
import { canDelete } from "../../lib/permissions";

const statusLabel=(value:string)=>value.toLowerCase().replaceAll("_"," ").replace(/^./,(letter)=>letter.toUpperCase());
const localDate=(value:string)=>new Intl.DateTimeFormat(undefined,{day:"numeric",month:"short",year:"numeric"}).format(new Date(`${value.slice(0,10)}T00:00:00`));

export function LabourReconciliationPage(){
  const {token,user}=useAuth();const location=useLocation();
  const mode=location.pathname.endsWith("settlement-history")?"SETTLEMENT":"EARNING";
  const workspaceId=user?.workspaceId??"";const farmId=getActiveFarmId()??"";const seasonId=getActiveSeasonId()??"";
  const permitted=Boolean(user&&canDelete(user,"wages",workspaceId));
  const pageSize=window.matchMedia("(min-width: 768px)").matches?30:20;
  const [rows,setRows]=useState<Array<LegacyLabourEarningRecord|LabourSettlementHistoryRecord>>([]);
  const [summary,setSummary]=useState<LabourReconciliationSummary|null>(null);const [page,setPage]=useState(1);const [hasMore,setHasMore]=useState(false);const [requestSucceeded,setRequestSucceeded]=useState(false);
  const [search,setSearch]=useState("");const [debouncedSearch,setDebouncedSearch]=useState("");const [integrity,setIntegrity]=useState("");const [scope,setScope]=useState("");const [status,setStatus]=useState("");const [source,setSource]=useState("");const [from,setFrom]=useState("");const [to,setTo]=useState("");
  const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [selected,setSelected]=useState<Set<string>>(new Set());
  const [preview,setPreview]=useState<LabourCleanupPreview|null>(null);const [previewTargets,setPreviewTargets]=useState<LabourCleanupTarget[]>([]);
  const [cleanupMode,setCleanupMode]=useState<"SOURCE_ONLY"|"FULL_CASCADE">("SOURCE_ONLY");const [reason,setReason]=useState("");const [confirmation,setConfirmation]=useState("");const [financialConfirmation,setFinancialConfirmation]=useState("");const [busy,setBusy]=useState(false);

  useEffect(()=>{const timer=window.setTimeout(()=>setDebouncedSearch(search.trim()),300);return()=>window.clearTimeout(timer);},[search]);
  useEffect(()=>{setPage(1);setSelected(new Set());},[mode,debouncedSearch,integrity,scope,status,source,from,to]);
  const filters=useMemo<LabourReconciliationFilters>(()=>({page,pageSize,search:debouncedSearch||undefined,integrity:integrity||undefined,scope:scope||undefined,status:status||undefined,source:source||undefined,from:from||undefined,to:to||undefined}),[page,pageSize,debouncedSearch,integrity,scope,status,source,from,to]);
  const load=useCallback(async(signal?:AbortSignal)=>{
    if(!token||!workspaceId||!farmId||!seasonId)return;
    setLoading(true);setError("");setRequestSucceeded(false);
    try{
      if(mode==="EARNING"){
        const response=await fetchLegacyLabourEarnings(token,workspaceId,farmId,seasonId,{...filters,signal});setRows(response.earnings);setSummary(response.summary);setHasMore(response.pageInfo.hasMore);
      }else{
        const response=await fetchLabourSettlementHistory(token,workspaceId,farmId,seasonId,{...filters,signal});setRows(response.settlements);setSummary(response.summary);setHasMore(response.pageInfo.hasMore);
      }
      setRequestSucceeded(true);
    }catch(caught){if(caught instanceof DOMException&&caught.name==="AbortError")return;console.error("Labour reconciliation request failed",{mode,workspaceId,farmId,seasonId,filters,error:caught});setRows([]);setSummary(null);setHasMore(false);setSelected(new Set());setError(mode==="SETTLEMENT"?"Settlement history could not be loaded.":"Legacy earnings could not be loaded.");}finally{if(!signal?.aborted)setLoading(false);}
  },[token,workspaceId,farmId,seasonId,mode,filters]);
  useEffect(()=>{const controller=new AbortController();void load(controller.signal);return()=>controller.abort();},[load]);

  const toggle=(id:string)=>setSelected((current)=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next;});
  const currentTargets=()=>rows.filter((row)=>selected.has(row.id)).map((row)=>({entityType:mode,id:row.id} as LabourCleanupTarget));
  const openPreview=async(targets=currentTargets())=>{if(!token||!targets.length)return;setBusy(true);setError("");try{const response=await previewLabourDataCleanup(token,workspaceId,{farmId,seasonId,targets});setPreviewTargets(targets);setPreview(response.preview);setCleanupMode(response.preview.requiresCascade?"FULL_CASCADE":"SOURCE_ONLY");}catch(caught){setError(caught instanceof Error?caught.message:"Cleanup preview failed.");}finally{setBusy(false);}};
  const selectMatching=async(selectionMode:"ALL_MATCHING"|"SOURCE_ONLY_ELIGIBLE")=>{if(!token)return;setBusy(true);try{const response=await resolveLabourCleanupSelection(token,workspaceId,farmId,seasonId,mode,filters,selectionMode);if(response.truncated)throw new Error("More than 5,000 records match. Narrow the filters before cleanup.");setSelected(new Set(response.targets.map((item)=>item.id)));}catch(caught){setError(caught instanceof Error?caught.message:"Selection failed.");}finally{setBusy(false);}};
  const execute=async()=>{if(!token||!preview)return;setBusy(true);try{const response=await executeLabourDataCleanup(token,workspaceId,{farmId,seasonId,targets:previewTargets,mode:cleanupMode,reason,confirmation:confirmation as "DELETE LABOUR DATA",financialConfirmation});const deleted=new Set(response.result.deleted.map((item)=>item.id));await Promise.all([offlineDb.labourEarnings.bulkDelete([...deleted]),offlineDb.labourWageSettlements.bulkDelete([...deleted])]);const queued=await offlineDb.pendingMutations.where("workspaceId").equals(workspaceId).toArray();await offlineDb.pendingMutations.bulkDelete(queued.filter((item)=>deleted.has((item.payload as {id?:string})?.id??"")).map((item)=>item.id));setPreview(null);setSelected(new Set());setConfirmation("");setFinancialConfirmation("");setReason("");window.dispatchEvent(new CustomEvent("muzare-data-refresh"));await load();}catch(caught){setError(caught instanceof Error?caught.message:"Cleanup failed.");}finally{setBusy(false);}};
  const hasActiveFilters=Boolean(debouncedSearch||integrity||scope||status||source||from||to);
  const clearFilters=()=>{setSearch("");setDebouncedSearch("");setIntegrity("");setScope("");setStatus("");setSource("");setFrom("");setTo("");setPage(1);setSelected(new Set());};

  return <section className="labour-reconciliation" aria-busy={loading}>
    <header className="labour-reconciliation__header"><div><span className="eyebrow">Temporary reconciliation</span><h1>{mode==="EARNING"?"Legacy Earnings":"Settlement History"}</h1><p>{mode==="EARNING"?"Inspect every historical labour earning and its financial links.":"Review active, paid, voided, reversed, and orphaned settlements."}</p></div>{permitted?<span className="cleanup-permission"><Trash2 size={14}/> Admin cleanup enabled</span>:null}</header>
    <div className={`labour-reconciliation__summary${loading?" is-loading":""}`}>{["Records","Gross value","Orphaned","Source-only eligible"].map((label,index)=><article key={label}><span>{label}</span><strong>{loading||!summary?"—":index===0?summary.totalCount:index===1?formatMoney(summary.totalAmount):index===2?summary.orphanedCount:summary.sourceOnlyEligibleCount}</strong></article>)}</div>
    <div className="labour-reconciliation__filters"><label className="reconciliation-search"><Search size={16}/><input value={search} onChange={(event)=>setSearch(event.target.value)} placeholder={mode==="EARNING"?"Search reference, recipient, work":"Search settlement, recipient, due"}/></label><select aria-label="Integrity status" value={integrity} onChange={(event)=>setIntegrity(event.target.value)}><option value="">All integrity states</option>{["ACTIVE","UNSETTLED","INCLUDED_IN_SETTLEMENT","PAID","PARTIALLY_PAID","VOIDED","REVERSED","ORPHANED","DUPLICATE_CANDIDATE","MISSING_RECIPIENT","REQUIRES_REVIEW"].map((value)=><option key={value} value={value}>{statusLabel(value)}</option>)}</select><select aria-label="Recipient scope" value={scope} onChange={(event)=>setScope(event.target.value)}><option value="">Individual and group</option><option value="individual">Individual</option><option value="group">Group</option></select><select aria-label="Record status" value={status} onChange={(event)=>setStatus(event.target.value)}><option value="">All record statuses</option>{(mode==="EARNING"?["pending_settlement","settled","voided"]:["posted","paid","voided","reversed","deleted"]).map((value)=><option key={value} value={value}>{statusLabel(value)}</option>)}</select><select aria-label="Source classification" value={source} onChange={(event)=>setSource(event.target.value)}><option value="">Current and legacy</option><option value="CURRENT">Current</option><option value="LEGACY">Legacy</option></select><label><span>From</span><input type="date" value={from} onChange={(event)=>setFrom(event.target.value)}/></label><label><span>To</span><input type="date" value={to} onChange={(event)=>setTo(event.target.value)}/></label><button type="button" className="clear-filters-button" disabled={!hasActiveFilters} onClick={clearFilters}>Clear filters</button></div>
    {permitted?<div className="cleanup-toolbar"><div><CheckSquare size={16}/>{requestSucceeded&&!loading&&!error?<strong>{selected.size} selected</strong>:<strong>Selection unavailable</strong>}</div><button type="button" disabled={!requestSucceeded||loading||Boolean(error)||!rows.length||busy} onClick={()=>setSelected(new Set(rows.map((row)=>row.id)))}>Current page</button><button type="button" disabled={!requestSucceeded||loading||Boolean(error)||busy} onClick={()=>void selectMatching("ALL_MATCHING")}>All matching filters</button><button type="button" disabled={!requestSucceeded||loading||Boolean(error)||busy} onClick={()=>void selectMatching("SOURCE_ONLY_ELIGIBLE")}>Eligible legacy records</button><button type="button" disabled={!requestSucceeded||loading||Boolean(error)||!selected.size||busy} className="danger-outline" onClick={()=>void openPreview()}>Preview deletion</button><button type="button" disabled={!requestSucceeded||loading||Boolean(error)||!selected.size} onClick={()=>setSelected(new Set())}>Clear</button></div>:null}
    {error&&!loading?<div className="reconciliation-error" role="alert"><AlertTriangle size={18}/><span><strong>{error}</strong><small>Retry the request. If the issue continues, check the API logs.</small></span><button type="button" onClick={()=>void load()}>Retry</button></div>:null}
    {loading?<div className="reconciliation-skeletons" aria-label="Loading labour history">{Array.from({length:5},(_,index)=><div key={index}/>)}</div>:error?null:requestSucceeded&&!rows.length?<div className="reconciliation-empty"><strong>{hasActiveFilters?mode==="SETTLEMENT"?"No settlements match these filters.":"No earnings match these filters.":mode==="SETTLEMENT"?"No settlement history yet.":"No legacy earnings yet."}</strong></div>:requestSucceeded?<div className="reconciliation-list">{rows.map((row)=><HistoryCard key={row.id} row={row} mode={mode} selectable={permitted} selected={selected.has(row.id)} onToggle={()=>toggle(row.id)}/>)}</div>:null}
    {requestSucceeded&&summary&&!error?<footer className="reconciliation-pagination"><span>Page {page} · {rows.length} of {summary.totalCount}</span><div><button type="button" disabled={page===1||loading} onClick={()=>setPage((value)=>value-1)}><ChevronLeft size={16}/> Previous</button><button type="button" disabled={!hasMore||loading} onClick={()=>setPage((value)=>value+1)}>Next <ChevronRight size={16}/></button></div></footer>:null}
    {preview?<div className="cleanup-modal-backdrop" role="presentation"><section className="cleanup-modal" role="dialog" aria-modal="true" aria-labelledby="cleanup-title"><header><div><span className="eyebrow">Labour Data Cleanup</span><h2 id="cleanup-title">Review permanent deletion</h2></div><button type="button" aria-label="Close" onClick={()=>setPreview(null)}><X size={20}/></button></header><div className="cleanup-modal__warning"><AlertTriangle size={20}/><p>{preview.financialEffects?"This deletion will also remove a posted payment and reverse/remove its account impact.":"This operation permanently removes the selected source data."}</p></div>{preview.blocked?<div className="reconciliation-error">{preview.blockedReasons.join(" ")}</div>:null}<div className="cleanup-dependencies">{preview.dependencies.map((item)=><article key={item.kind}><div><strong>{item.kind}</strong><span>{item.count}</span></div><small>{item.message}</small><em className={`integrity-chip integrity-chip--${item.classification.toLowerCase()}`}>{statusLabel(item.classification)}</em></article>)}</div><label>Deletion level<select value={cleanupMode} onChange={(event)=>setCleanupMode(event.target.value as typeof cleanupMode)}><option value="SOURCE_ONLY" disabled={preview.requiresCascade}>Delete source only</option><option value="FULL_CASCADE">Full cascade hard delete</option></select></label><label>Reason<textarea value={reason} onChange={(event)=>setReason(event.target.value)} placeholder="Why is this cleanup required?"/></label><label>Type DELETE LABOUR DATA<input value={confirmation} onChange={(event)=>setConfirmation(event.target.value)}/></label>{preview.financialEffects?<label>Type DELETE FINANCIAL HISTORY<input value={financialConfirmation} onChange={(event)=>setFinancialConfirmation(event.target.value)}/></label>:null}<footer><button type="button" onClick={()=>setPreview(null)}>Cancel</button><button type="button" className="danger-button" disabled={busy||preview.blocked||reason.trim().length<3||confirmation!=="DELETE LABOUR DATA"||(preview.financialEffects&&financialConfirmation!=="DELETE FINANCIAL HISTORY")} onClick={()=>void execute()}>{busy?"Deleting…":"Permanently delete"}</button></footer></section></div>:null}
  </section>;
}

function HistoryCard({row,mode,selectable,selected,onToggle}:{row:LegacyLabourEarningRecord|LabourSettlementHistoryRecord;mode:"EARNING"|"SETTLEMENT";selectable:boolean;selected:boolean;onToggle:()=>void}){
  const earning=mode==="EARNING"?row as LegacyLabourEarningRecord:null;const settlement=mode==="SETTLEMENT"?row as LabourSettlementHistoryRecord:null;
  const recipient=row.recipientName??"Recipient unavailable";const reference=earning?.reference??settlement?.settlementNumber??row.id;
  return <article className={`reconciliation-card${selected?" is-selected":""}`}><header>{selectable?<input type="checkbox" checked={selected} onChange={onToggle} aria-label={`Select ${reference}`}/>:null}<div><strong>{recipient}</strong><span>{reference} · {earning?localDate(earning.workDate):`${localDate(settlement!.fromDate)} – ${localDate(settlement!.toDate)}`}</span></div><em className={`integrity-chip integrity-chip--${row.integrityStatus.toLowerCase()}`}>{statusLabel(row.integrityStatus)}</em></header><div className="reconciliation-card__money"><span>Gross amount<strong>{formatMoney(earning?.grossAmount??settlement!.grossAmount)}</strong></span>{settlement?<><span>Advances<strong>{formatMoney(settlement.advancesApplied)}</strong></span><span>Paid<strong>{formatMoney(settlement.paymentsMade)}</strong></span><span className="primary-value">Outstanding<strong>{formatMoney(settlement.outstandingBalance)}</strong></span></>:null}</div><div className="reconciliation-card__details"><span><b>Scope</b>{statusLabel(row.recipientScope)}</span><span><b>Source</b>{earning?.sourceModule??settlement?.settlementType}</span><span><b>Settlement</b>{earning?.settlementReference??settlement?.dueReference??"Not linked"}</span><span><b>Voucher</b>{row.voucherReferences.join(", ")||"Not linked"}</span></div>{earning?<p>{earning.description}</p>:<p>{settlement!.sourceAttendanceCount} attendance · {settlement!.sourceEarningCount} earnings · {statusLabel(settlement!.paymentStatus)}</p>}</article>;
}
