type ReportPdfContext = {
  workspace: string;
  farm: string;
  season: string;
  generatedAt: string;
  generatedBy: string;
};

type ReportPdfSpec = {
  title: string;
  filename: string;
  rangeLabel: string;
  context?: ReportPdfContext | null;
  orientation?: "portrait" | "landscape";
  rows: unknown[][];
  language?: string;
  direction?: "ltr" | "rtl";
  variant?: "standard" | "minimal";
};

type NormalizedRow = string[];

type MetricsBlock = {
  kind: "metrics";
  title?: string;
  rows: Array<[string, string]>;
};

type TotalBlock = {
  kind: "total";
  label: string;
  value: string;
};

type TableBlock = {
  kind: "table";
  title?: string;
  summary?: string;
  headers: string[];
  rows: string[][];
};

type ReportBlock = MetricsBlock | TotalBlock | TableBlock;

type PdfColor = [number, number, number];
type TextAlign = "left" | "center" | "right";

type PageSurface = {
  canvas: HTMLCanvasElement;
  context: CanvasRenderingContext2D;
  cursorY: number;
  firstPage: boolean;
};

type LocaleLabels = {
  workspace: string;
  farm: string;
  season: string;
  generated: string;
  generatedBy: string;
  noRecords: string;
  continued: string;
  metric: string;
  allRecords: string;
};

const BRAND = "Muzare";
const ARABIC_FONT_URL = new URL("../assets/fonts/NotoSansArabic-Regular.ttf", import.meta.url).href;
const REPORT_FONT_FAMILY = "MuzareReport";
const FONT_STACK = `"${REPORT_FONT_FAMILY}", Inter, "Segoe UI", Arial, sans-serif`;

const NAVY: PdfColor = [14, 43, 58];
const NAVY_SOFT: PdfColor = [31, 69, 82];
const GREEN: PdfColor = [39, 116, 67];
const GREEN_DARK: PdfColor = [29, 91, 50];
const GREEN_SOFT: PdfColor = [239, 247, 241];
const GREEN_FAINT: PdfColor = [247, 251, 248];
const BORDER: PdfColor = [214, 225, 218];
const TEXT: PdfColor = [35, 52, 43];
const MUTED: PdfColor = [99, 116, 104];
const WHITE: PdfColor = [255, 255, 255];

const CANVAS_SCALE = 2;
const PAGE_MARGIN = 34;
const PAGE_BOTTOM = 36;
const TABLE_CELL_PADDING_X = 6;
const TABLE_CELL_PADDING_Y = 5;

const localeLabels: Record<"en" | "ar" | "ur", LocaleLabels> = {
  en: {
    workspace: "Workspace",
    farm: "Farm",
    season: "Season",
    generated: "Generated",
    generatedBy: "Generated by",
    noRecords: "No records found",
    continued: "Continued",
    metric: "Metric",
    allRecords: "All records",
  },
  ar: {
    workspace: "مساحة العمل",
    farm: "المزرعة",
    season: "الموسم",
    generated: "تاريخ الإنشاء",
    generatedBy: "أنشأه",
    noRecords: "لا توجد سجلات",
    continued: "متابعة",
    metric: "مؤشر",
    allRecords: "جميع السجلات",
  },
  ur: {
    workspace: "ورک اسپیس",
    farm: "فارم",
    season: "سیزن",
    generated: "تیار کردہ",
    generatedBy: "تیار کرنے والا",
    noRecords: "کوئی ریکارڈ موجود نہیں",
    continued: "جاری",
    metric: "اشاریہ",
    allRecords: "تمام ریکارڈز",
  },
};

let reportFontPromise: Promise<boolean> | null = null;

const rgb = ([red, green, blue]: PdfColor, alpha = 1) => `rgba(${red}, ${green}, ${blue}, ${alpha})`;

const clamp = (value: number, minimum: number, maximum: number) => Math.min(Math.max(value, minimum), maximum);

const normalizeFilename = (filename: string) => {
  const base = filename.replace(/\.csv$/i, "").replace(/\.pdf$/i, "");
  const safe = base
    .normalize("NFKD")
    .replace(/[^\p{L}\p{N}._-]+/gu, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
  return `${safe || "muzare-report"}.pdf`;
};

const titleFromFilename = (filename: string) => filename
  .replace(/\.(csv|pdf)$/i, "")
  .replace(/[-_]+/g, " ")
  .replace(/\b\w/g, (value) => value.toUpperCase());

const normalizeValue = (value: unknown) => {
  if (value === null || value === undefined) return "";
  if (typeof value === "number") {
    return new Intl.NumberFormat("en-US", { maximumFractionDigits: 2 }).format(value);
  }
  if (typeof value === "boolean") return value ? "Yes" : "No";
  return String(value).replace(/\s+/g, " ").trim();
};

const normalizeRows = (rows: unknown[][]): NormalizedRow[] => rows.map((row) => row.map(normalizeValue));
const rowIsBlank = (row: NormalizedRow) => row.every((cell) => !cell);
const trimTrailingEmptyCells = (row: NormalizedRow) => {
  const next = [...row];
  while (next.length > 0 && !next[next.length - 1]) next.pop();
  return next;
};

const splitIntoBlocks = (rows: NormalizedRow[]) => {
  const blocks: NormalizedRow[][] = [];
  let current: NormalizedRow[] = [];
  for (const sourceRow of rows) {
    const row = trimTrailingEmptyCells(sourceRow);
    if (rowIsBlank(row)) {
      if (current.length > 0) blocks.push(current);
      current = [];
      continue;
    }
    current.push(row);
  }
  if (current.length > 0) blocks.push(current);
  return blocks;
};

const looksLikeExportHeader = (block: NormalizedRow[]) => {
  if (block.length < 2) return false;
  const first = block[0]?.[0]?.toLocaleLowerCase() ?? "";
  return first === BRAND.toLocaleLowerCase() && block.every((row) => row.length <= 2);
};

const parseBlocks = (rows: unknown[][], labels: LocaleLabels): ReportBlock[] => {
  const rawBlocks = splitIntoBlocks(normalizeRows(rows));
  return rawBlocks.flatMap<ReportBlock>((block, blockIndex) => {
    if (blockIndex === 0 && looksLikeExportHeader(block)) return [];
    const maxColumns = Math.max(...block.map((row) => row.length));

    if (maxColumns <= 2) {
      const firstRowIsTitle = block.length > 1 && block[0].length <= 2 && !block[0][1];
      const title = firstRowIsTitle ? block[0][0] : undefined;
      const sourceRows = firstRowIsTitle ? block.slice(1) : block;
      const metricRows = sourceRows
        .filter((row) => row.some(Boolean))
        .map((row, index) => [row[0] || `${labels.metric} ${index + 1}`, row[1] || "—"] as [string, string]);

      if (blockIndex === rawBlocks.length - 1 && metricRows.length === 1) {
        return [{ kind: "total", label: metricRows[0][0], value: metricRows[0][1] }];
      }
      return metricRows.length > 0 ? [{ kind: "metrics", title, rows: metricRows }] : [];
    }

    let title: string | undefined;
    let summary: string | undefined;
    let tableRows = block;
    if (block.length > 1 && block[0].length < maxColumns) {
      title = block[0][0] || undefined;
      const summaryParts = block[0].slice(1).filter(Boolean);
      summary = summaryParts.length > 0 ? summaryParts.join(" • ") : undefined;
      tableRows = block.slice(1);
    }
    if (tableRows.length === 0) return [];
    const headers = Array.from(
      { length: maxColumns },
      (_, index) => tableRows[0]?.[index] || `Column ${index + 1}`,
    );
    const body = tableRows.slice(1).map((row) => Array.from({ length: maxColumns }, (_, index) => row[index] || ""));
    return [{ kind: "table", title, summary, headers, rows: body }];
  });
};

const resolveLocale = (language?: string) => {
  const normalized = (language || "en").toLowerCase();
  if (normalized.startsWith("ur")) return "ur" as const;
  if (normalized.startsWith("ar")) return "ar" as const;
  return "en" as const;
};

const ensureReportFont = async () => {
  if (reportFontPromise) return reportFontPromise;
  reportFontPromise = (async () => {
    if (typeof document === "undefined" || typeof FontFace === "undefined" || !document.fonts) return false;
    try {
      const face = new FontFace(REPORT_FONT_FAMILY, `url(${ARABIC_FONT_URL})`, {
        style: "normal",
        weight: "normal",
      });
      const loaded = await face.load();
      document.fonts.add(loaded);
      await document.fonts.ready;
      return document.fonts.check(`12px "${REPORT_FONT_FAMILY}"`);
    } catch {
      return false;
    }
  })();
  return reportFontPromise;
};

const roundedRectPath = (
  context: CanvasRenderingContext2D,
  x: number,
  y: number,
  width: number,
  height: number,
  radius: number,
) => {
  const safeRadius = Math.min(radius, width / 2, height / 2);
  context.beginPath();
  context.moveTo(x + safeRadius, y);
  context.lineTo(x + width - safeRadius, y);
  context.quadraticCurveTo(x + width, y, x + width, y + safeRadius);
  context.lineTo(x + width, y + height - safeRadius);
  context.quadraticCurveTo(x + width, y + height, x + width - safeRadius, y + height);
  context.lineTo(x + safeRadius, y + height);
  context.quadraticCurveTo(x, y + height, x, y + height - safeRadius);
  context.lineTo(x, y + safeRadius);
  context.quadraticCurveTo(x, y, x + safeRadius, y);
  context.closePath();
};

const fillRoundedRect = (
  context: CanvasRenderingContext2D,
  x: number,
  y: number,
  width: number,
  height: number,
  radius: number,
  fillStyle: string | CanvasGradient,
) => {
  roundedRectPath(context, x, y, width, height, radius);
  context.fillStyle = fillStyle;
  context.fill();
};

const strokeRoundedRect = (
  context: CanvasRenderingContext2D,
  x: number,
  y: number,
  width: number,
  height: number,
  radius: number,
  strokeStyle: string,
  lineWidth = 1,
) => {
  roundedRectPath(context, x, y, width, height, radius);
  context.strokeStyle = strokeStyle;
  context.lineWidth = lineWidth;
  context.stroke();
};

const setCanvasFont = (context: CanvasRenderingContext2D, size: number, weight = 400) => {
  context.font = `${weight} ${size}px ${FONT_STACK}`;
};

const splitLongToken = (context: CanvasRenderingContext2D, token: string, maxWidth: number) => {
  const parts: string[] = [];
  let current = "";
  for (const character of Array.from(token)) {
    const candidate = `${current}${character}`;
    if (current && context.measureText(candidate).width > maxWidth) {
      parts.push(current);
      current = character;
    } else {
      current = candidate;
    }
  }
  if (current) parts.push(current);
  return parts;
};

const wrapText = (
  context: CanvasRenderingContext2D,
  rawText: string,
  maxWidth: number,
  maxLines = Number.POSITIVE_INFINITY,
) => {
  const text = rawText || "—";
  const tokens = text.split(/\s+/u).filter(Boolean);
  const lines: string[] = [];
  let current = "";

  const pushCurrent = () => {
    if (current) lines.push(current);
    current = "";
  };

  for (const token of tokens.length > 0 ? tokens : [text]) {
    const tokenParts = context.measureText(token).width > maxWidth ? splitLongToken(context, token, maxWidth) : [token];
    for (const part of tokenParts) {
      const candidate = current ? `${current} ${part}` : part;
      if (current && context.measureText(candidate).width > maxWidth) {
        pushCurrent();
        current = part;
      } else {
        current = candidate;
      }
      if (lines.length >= maxLines) break;
    }
    if (lines.length >= maxLines) break;
  }
  if (lines.length < maxLines) pushCurrent();

  if (lines.length > maxLines) lines.length = maxLines;
  if (Number.isFinite(maxLines) && lines.length === maxLines) {
    const combined = lines.join(" ");
    if (combined.length < text.length) {
      let finalLine = lines[maxLines - 1] || "";
      while (finalLine && context.measureText(`${finalLine}…`).width > maxWidth) finalLine = finalLine.slice(0, -1);
      lines[maxLines - 1] = `${finalLine}…`;
    }
  }
  return lines.length > 0 ? lines : ["—"];
};

const drawTextLines = (
  context: CanvasRenderingContext2D,
  lines: string[],
  x: number,
  y: number,
  lineHeight: number,
  align: TextAlign,
  direction: "ltr" | "rtl",
  color: PdfColor,
) => {
  context.save();
  context.fillStyle = rgb(color);
  context.textAlign = align;
  context.textBaseline = "alphabetic";
  context.direction = direction;
  lines.forEach((line, index) => context.fillText(line, x, y + index * lineHeight));
  context.restore();
};

const valueLooksNumeric = (value: string) => {
  const normalized = value.replace(/[,%\s]/g, "").replace(/^[-+]/, "");
  return normalized !== "" && Number.isFinite(Number(normalized));
};

const headerSuggestsPercent = (header: string) => /share|percent|percentage|حصہ|فیصد|نسبت|٪/iu.test(header);

const calculateColumnWidths = (
  context: CanvasRenderingContext2D,
  headers: string[],
  rows: string[][],
  availableWidth: number,
  fontSize: number,
) => {
  const columnCount = headers.length;
  const samples = rows.slice(0, 40);
  setCanvasFont(context, fontSize, 400);

  const numericColumns = headers.map((_, columnIndex) => {
    const values = samples.map((row) => row[columnIndex]).filter(Boolean);
    if (values.length === 0) return false;
    return values.filter(valueLooksNumeric).length / values.length >= 0.7;
  });

  const minimums = headers.map((_, index) => numericColumns[index]
    ? (columnCount > 10 ? 34 : 44)
    : (columnCount > 10 ? 46 : 62));
  const maximums = headers.map((header, index) => {
    if (numericColumns[index]) return columnCount > 10 ? 68 : 90;
    if (/description|notes|remarks|تفصیل|نوٹس|ملاحظات|بيان/iu.test(header)) return 210;
    return columnCount > 10 ? 110 : 165;
  });

  const natural = headers.map((header, columnIndex) => {
    setCanvasFont(context, fontSize + 0.4, 700);
    let measured = context.measureText(header || `Column ${columnIndex + 1}`).width + 18;
    setCanvasFont(context, fontSize, 400);
    for (const row of samples) measured = Math.max(measured, context.measureText(row[columnIndex] || "").width + 18);
    return clamp(measured, minimums[columnIndex], maximums[columnIndex]);
  });

  const minimumTotal = minimums.reduce((sum, value) => sum + value, 0);
  if (minimumTotal >= availableWidth) {
    const equal = availableWidth / columnCount;
    return headers.map((_, index) => Math.max(columnCount > 10 ? 28 : 38, equal * (numericColumns[index] ? 0.85 : 1.08)))
      .map((width, _, all) => width * (availableWidth / all.reduce((sum, value) => sum + value, 0)));
  }

  const widths = [...minimums];
  let remaining = availableWidth - minimumTotal;
  const demands = natural.map((value, index) => Math.max(value - minimums[index], 0.1));
  const totalDemand = demands.reduce((sum, value) => sum + value, 0);
  widths.forEach((_, index) => {
    const addition = Math.min(demands[index], remaining * (demands[index] / totalDemand));
    widths[index] += addition;
  });

  const used = widths.reduce((sum, value) => sum + value, 0);
  remaining = availableWidth - used;
  if (remaining > 0.5) {
    const growWeights = widths.map((_, index) => numericColumns[index] ? 0.55 : 1);
    const weightTotal = growWeights.reduce((sum, value) => sum + value, 0);
    widths.forEach((_, index) => { widths[index] += remaining * (growWeights[index] / weightTotal); });
  }
  return widths;
};

const createPageCanvas = (pageWidth: number, pageHeight: number) => {
  const canvas = document.createElement("canvas");
  canvas.width = Math.ceil(pageWidth * CANVAS_SCALE);
  canvas.height = Math.ceil(pageHeight * CANVAS_SCALE);
  const context = canvas.getContext("2d", { alpha: false });
  if (!context) throw new Error("Unable to initialize report canvas.");
  context.scale(CANVAS_SCALE, CANVAS_SCALE);
  context.fillStyle = rgb(WHITE);
  context.fillRect(0, 0, pageWidth, pageHeight);
  context.imageSmoothingEnabled = true;
  context.imageSmoothingQuality = "high";
  return { canvas, context };
};

const renderHeader = (
  surface: PageSurface,
  spec: ReportPdfSpec,
  pageWidth: number,
  rtl: boolean,
  labels: LocaleLabels,
) => {
  const { context, firstPage } = surface;
  const title = normalizeValue(spec.title) || titleFromFilename(spec.filename);
  const rangeLabel = normalizeValue(spec.rangeLabel) || labels.allRecords;
  const titleAlign: TextAlign = rtl ? "right" : "left";
  const titleX = rtl ? pageWidth - PAGE_MARGIN : PAGE_MARGIN;
  const rangeAlign: TextAlign = rtl ? "left" : "right";

  const headerHeight = firstPage ? 78 : 48;
  const gradient = context.createLinearGradient(0, 0, pageWidth, 0);
  if (rtl) {
    gradient.addColorStop(0, rgb(NAVY));
    gradient.addColorStop(1, rgb(GREEN_DARK));
  } else {
    gradient.addColorStop(0, rgb(GREEN_DARK));
    gradient.addColorStop(1, rgb(NAVY));
  }
  context.fillStyle = gradient;
  context.fillRect(0, 0, pageWidth, headerHeight);

  context.fillStyle = rgb(GREEN);
  context.fillRect(rtl ? pageWidth - 5 : 0, 0, 5, headerHeight);

  setCanvasFont(context, firstPage ? 9 : 8, 800);
  drawTextLines(context, [BRAND.toUpperCase()], titleX, firstPage ? 24 : 20, 10, titleAlign, rtl ? "rtl" : "ltr", WHITE);

  setCanvasFont(context, firstPage ? 18 : 12, 750);
  const titleLines = wrapText(context, title, pageWidth * (firstPage ? 0.58 : 0.64), firstPage ? 2 : 1);
  drawTextLines(context, titleLines, titleX, firstPage ? 50 : 36, firstPage ? 20 : 14, titleAlign, rtl ? "rtl" : "ltr", WHITE);

  setCanvasFont(context, firstPage ? 8 : 7.5, 600);
  const rangeWidth = clamp(context.measureText(rangeLabel).width + 20, 92, pageWidth * 0.34);
  const rangeHeight = firstPage ? 30 : 24;
  const rangeY = firstPage ? 24 : 12;
  const rangeLeft = rtl ? PAGE_MARGIN : pageWidth - PAGE_MARGIN - rangeWidth;
  fillRoundedRect(context, rangeLeft, rangeY, rangeWidth, rangeHeight, rangeHeight / 2, "rgba(255,255,255,0.16)");
  strokeRoundedRect(context, rangeLeft, rangeY, rangeWidth, rangeHeight, rangeHeight / 2, "rgba(255,255,255,0.25)", 0.8);
  const rangeTextX = rtl ? rangeLeft + 10 : rangeLeft + rangeWidth - 10;
  drawTextLines(
    context,
    wrapText(context, rangeLabel, rangeWidth - 20, 1),
    rangeTextX,
    rangeY + (firstPage ? 19 : 16),
    10,
    rangeAlign,
    rtl ? "rtl" : "ltr",
    WHITE,
  );

  surface.cursorY = headerHeight + (firstPage ? 14 : 10);
};

const renderContextCards = (
  surface: PageSurface,
  spec: ReportPdfSpec,
  pageWidth: number,
  rtl: boolean,
  labels: LocaleLabels,
  orientation: "portrait" | "landscape",
) => {
  if (!surface.firstPage || !spec.context) return;
  const { context } = surface;
  const contextRows = ([
    [labels.workspace, normalizeValue(spec.context.workspace)],
    [labels.farm, normalizeValue(spec.context.farm)],
    [labels.season, normalizeValue(spec.context.season)],
    [labels.generated, normalizeValue(spec.context.generatedAt)],
    [labels.generatedBy, normalizeValue(spec.context.generatedBy)],
  ] as Array<[string, string]>).filter(([, value]) => Boolean(value && value !== "—"));
  if (contextRows.length === 0) return;

  const availableWidth = pageWidth - PAGE_MARGIN * 2;
  const columns = orientation === "landscape" ? Math.min(4, contextRows.length) : Math.min(3, contextRows.length);
  const gap = 7;
  const cardHeight = 38;
  const cardWidth = (availableWidth - gap * (columns - 1)) / columns;
  const rows = Math.ceil(contextRows.length / columns);

  contextRows.forEach(([label, value], index) => {
    const rowIndex = Math.floor(index / columns);
    const columnIndex = index % columns;
    const visualColumn = rtl ? columns - columnIndex - 1 : columnIndex;
    const x = PAGE_MARGIN + visualColumn * (cardWidth + gap);
    const y = surface.cursorY + rowIndex * (cardHeight + gap);
    fillRoundedRect(context, x, y, cardWidth, cardHeight, 6, rgb(GREEN_FAINT));
    strokeRoundedRect(context, x, y, cardWidth, cardHeight, 6, rgb(BORDER), 0.7);
    context.fillStyle = rgb(GREEN);
    context.fillRect(rtl ? x + cardWidth - 3 : x, y + 7, 3, cardHeight - 14);

    const align: TextAlign = rtl ? "right" : "left";
    const textX = rtl ? x + cardWidth - 10 : x + 10;
    setCanvasFont(context, 6.5, 600);
    drawTextLines(context, wrapText(context, label, cardWidth - 20, 1), textX, y + 13, 8, align, rtl ? "rtl" : "ltr", MUTED);
    setCanvasFont(context, 8.2, 750);
    drawTextLines(context, wrapText(context, value, cardWidth - 20, 1), textX, y + 29, 10, align, rtl ? "rtl" : "ltr", TEXT);
  });

  surface.cursorY += rows * (cardHeight + gap) + 5;
};

const renderSectionTitle = (
  surface: PageSurface,
  title: string | undefined,
  summary: string | undefined,
  pageWidth: number,
  rtl: boolean,
  continued: boolean,
  labels: LocaleLabels,
) => {
  if (!title) return;
  const { context } = surface;
  const availableWidth = pageWidth - PAGE_MARGIN * 2;
  const displayTitle = continued ? `${title} - ${labels.continued}` : title;
  const height = 28;
  fillRoundedRect(context, PAGE_MARGIN, surface.cursorY, availableWidth, height, 6, rgb(GREEN_SOFT));
  context.fillStyle = rgb(GREEN);
  context.fillRect(rtl ? pageWidth - PAGE_MARGIN - 4 : PAGE_MARGIN, surface.cursorY + 5, 4, height - 10);

  const align: TextAlign = rtl ? "right" : "left";
  const titleX = rtl ? pageWidth - PAGE_MARGIN - 12 : PAGE_MARGIN + 12;
  setCanvasFont(context, 9.5, 800);
  drawTextLines(context, wrapText(context, displayTitle, availableWidth * 0.68, 1), titleX, surface.cursorY + 18, 11, align, rtl ? "rtl" : "ltr", NAVY);

  if (summary) {
    setCanvasFont(context, 7.2, 600);
    const summaryAlign: TextAlign = rtl ? "left" : "right";
    const summaryX = rtl ? PAGE_MARGIN + 10 : pageWidth - PAGE_MARGIN - 10;
    drawTextLines(context, wrapText(context, summary, availableWidth * 0.28, 1), summaryX, surface.cursorY + 18, 9, summaryAlign, rtl ? "rtl" : "ltr", MUTED);
  }
  surface.cursorY += height + 7;
};

const renderMetrics = (
  surface: PageSurface,
  block: MetricsBlock,
  pageWidth: number,
  pageHeight: number,
  rtl: boolean,
  orientation: "portrait" | "landscape",
  labels: LocaleLabels,
  requestNewPage: () => PageSurface,
) => {
  const availableWidth = pageWidth - PAGE_MARGIN * 2;
  const columns = orientation === "landscape"
    ? Math.min(5, block.rows.length)
    : Math.min(block.rows.length <= 4 ? 2 : 3, block.rows.length);
  const gap = 8;
  const cardHeight = 54;
  const rowsNeeded = Math.ceil(block.rows.length / Math.max(columns, 1));
  const requiredHeight = (block.title ? 35 : 0) + rowsNeeded * (cardHeight + gap) + 2;

  let activeSurface = surface;
  if (activeSurface.cursorY + requiredHeight > pageHeight - PAGE_BOTTOM) activeSurface = requestNewPage();
  renderSectionTitle(activeSurface, block.title, undefined, pageWidth, rtl, false, labels);

  const cardWidth = (availableWidth - gap * (columns - 1)) / columns;
  block.rows.forEach(([label, value], index) => {
    const rowIndex = Math.floor(index / columns);
    const columnIndex = index % columns;
    const visualColumn = rtl ? columns - columnIndex - 1 : columnIndex;
    const x = PAGE_MARGIN + visualColumn * (cardWidth + gap);
    const y = activeSurface.cursorY + rowIndex * (cardHeight + gap);

    fillRoundedRect(activeSurface.context, x, y, cardWidth, cardHeight, 7, rgb(WHITE));
    strokeRoundedRect(activeSurface.context, x, y, cardWidth, cardHeight, 7, rgb(BORDER), 0.8);
    activeSurface.context.fillStyle = rgb(GREEN);
    activeSurface.context.fillRect(x + 1, y + 1, cardWidth - 2, 3);

    const align: TextAlign = rtl ? "right" : "left";
    const textX = rtl ? x + cardWidth - 10 : x + 10;
    setCanvasFont(activeSurface.context, 7.2, 600);
    drawTextLines(activeSurface.context, wrapText(activeSurface.context, label, cardWidth - 20, 2), textX, y + 17, 9, align, rtl ? "rtl" : "ltr", MUTED);
    setCanvasFont(activeSurface.context, 13, 800);
    drawTextLines(activeSurface.context, wrapText(activeSurface.context, value, cardWidth - 20, 1), textX, y + 42, 14, align, rtl ? "rtl" : "ltr", NAVY);
  });
  activeSurface.cursorY += rowsNeeded * (cardHeight + gap) + 2;
  return activeSurface;
};

const renderTotal = (
  surface: PageSurface,
  block: TotalBlock,
  pageWidth: number,
  pageHeight: number,
  rtl: boolean,
  requestNewPage: () => PageSurface,
) => {
  let activeSurface = surface;
  const cardHeight = 64;
  if (activeSurface.cursorY + cardHeight > pageHeight - PAGE_BOTTOM) activeSurface = requestNewPage();
  const availableWidth = pageWidth - PAGE_MARGIN * 2;
  const gradient = activeSurface.context.createLinearGradient(PAGE_MARGIN, 0, pageWidth - PAGE_MARGIN, 0);
  gradient.addColorStop(0, rgb(NAVY));
  gradient.addColorStop(1, rgb(GREEN_DARK));
  fillRoundedRect(activeSurface.context, PAGE_MARGIN, activeSurface.cursorY, availableWidth, cardHeight, 9, gradient);

  const align: TextAlign = rtl ? "right" : "left";
  const textX = rtl ? pageWidth - PAGE_MARGIN - 16 : PAGE_MARGIN + 16;
  setCanvasFont(activeSurface.context, 8, 650);
  drawTextLines(activeSurface.context, [block.label || "Total"], textX, activeSurface.cursorY + 21, 10, align, rtl ? "rtl" : "ltr", WHITE);
  setCanvasFont(activeSurface.context, 20, 850);
  drawTextLines(activeSurface.context, [block.value || "—"], textX, activeSurface.cursorY + 49, 22, align, rtl ? "rtl" : "ltr", WHITE);
  activeSurface.cursorY += cardHeight + 4;
  return activeSurface;
};

const renderTable = (
  surface: PageSurface,
  block: TableBlock,
  pageWidth: number,
  pageHeight: number,
  rtl: boolean,
  orientation: "portrait" | "landscape",
  labels: LocaleLabels,
  requestNewPage: () => PageSurface,
) => {
  let activeSurface = surface;
  const availableWidth = pageWidth - PAGE_MARGIN * 2;
  const columnCount = block.headers.length;
  const dense = columnCount > 9;
  const fontSize = dense ? 5.8 : orientation === "landscape" ? 6.8 : 7.2;
  const headerFontSize = dense ? 5.8 : 7;
  const widths = calculateColumnWidths(activeSurface.context, block.headers, block.rows, availableWidth, fontSize);
  const logicalIndices = Array.from({ length: columnCount }, (_, index) => index);
  const visualIndices = rtl ? [...logicalIndices].reverse() : logicalIndices;
  const percentColumns = block.headers.map(headerSuggestsPercent);

  const measureHeaderHeight = () => {
    setCanvasFont(activeSurface.context, headerFontSize, 750);
    const maxLines = Math.max(...block.headers.map((header, index) => wrapText(activeSurface.context, header, widths[index] - TABLE_CELL_PADDING_X * 2, 2).length));
    return Math.max(28, maxLines * (headerFontSize + 2) + TABLE_CELL_PADDING_Y * 2 + 2);
  };
  const headerHeight = measureHeaderHeight();

  const drawHeaderRow = () => {
    let x = PAGE_MARGIN;
    for (const logicalIndex of visualIndices) {
      const width = widths[logicalIndex];
      activeSurface.context.fillStyle = rgb(NAVY_SOFT);
      activeSurface.context.fillRect(x, activeSurface.cursorY, width, headerHeight);
      activeSurface.context.strokeStyle = "rgba(255,255,255,0.18)";
      activeSurface.context.lineWidth = 0.6;
      activeSurface.context.strokeRect(x, activeSurface.cursorY, width, headerHeight);

      setCanvasFont(activeSurface.context, headerFontSize, 750);
      const lines = wrapText(activeSurface.context, block.headers[logicalIndex], width - TABLE_CELL_PADDING_X * 2, 2);
      const numeric = block.rows.slice(0, 20).filter((row) => row[logicalIndex]).filter((row) => valueLooksNumeric(row[logicalIndex])).length > 12;
      const align: TextAlign = numeric ? "center" : rtl ? "right" : "left";
      const textX = align === "center" ? x + width / 2 : align === "right" ? x + width - TABLE_CELL_PADDING_X : x + TABLE_CELL_PADDING_X;
      const totalTextHeight = (lines.length - 1) * (headerFontSize + 2);
      const baseline = activeSurface.cursorY + (headerHeight - totalTextHeight) / 2 + headerFontSize * 0.36;
      drawTextLines(activeSurface.context, lines, textX, baseline, headerFontSize + 2, align, rtl ? "rtl" : "ltr", WHITE);
      x += width;
    }
    activeSurface.cursorY += headerHeight;
  };

  const drawSectionAndHeader = (continued: boolean) => {
    renderSectionTitle(activeSurface, block.title, block.summary, pageWidth, rtl, continued, labels);
    drawHeaderRow();
  };

  const requiredTop = (block.title ? 35 : 0) + headerHeight + 26;
  if (activeSurface.cursorY + requiredTop > pageHeight - PAGE_BOTTOM) activeSurface = requestNewPage();
  drawSectionAndHeader(false);

  if (block.rows.length === 0) {
    const emptyHeight = 46;
    fillRoundedRect(activeSurface.context, PAGE_MARGIN, activeSurface.cursorY + 6, availableWidth, emptyHeight, 7, rgb(GREEN_FAINT));
    strokeRoundedRect(activeSurface.context, PAGE_MARGIN, activeSurface.cursorY + 6, availableWidth, emptyHeight, 7, rgb(BORDER), 0.8);
    setCanvasFont(activeSurface.context, 9, 650);
    drawTextLines(
      activeSurface.context,
      [labels.noRecords],
      rtl ? pageWidth - PAGE_MARGIN - 14 : PAGE_MARGIN + 14,
      activeSurface.cursorY + 34,
      11,
      rtl ? "right" : "left",
      rtl ? "rtl" : "ltr",
      MUTED,
    );
    activeSurface.cursorY += emptyHeight + 14;
    return activeSurface;
  }

  block.rows.forEach((row, rowIndex) => {
    setCanvasFont(activeSurface.context, fontSize, 400);
    const wrappedCells = block.headers.map((_, columnIndex) => {
      const raw = row[columnIndex] || "—";
      const display = percentColumns[columnIndex] && valueLooksNumeric(raw) && !raw.includes("%") ? `${raw}%` : raw;
      return wrapText(activeSurface.context, display, widths[columnIndex] - TABLE_CELL_PADDING_X * 2);
    });
    const maximumLines = Math.max(...wrappedCells.map((lines) => lines.length));
    const lineHeight = fontSize + 2.2;
    let lineOffset = 0;

    while (lineOffset < maximumLines) {
      let availableHeight = pageHeight - PAGE_BOTTOM - activeSurface.cursorY;
      let linesThatFit = Math.floor((availableHeight - TABLE_CELL_PADDING_Y * 2) / lineHeight);
      if (linesThatFit < 1) {
        activeSurface = requestNewPage();
        drawSectionAndHeader(true);
        availableHeight = pageHeight - PAGE_BOTTOM - activeSurface.cursorY;
        linesThatFit = Math.max(1, Math.floor((availableHeight - TABLE_CELL_PADDING_Y * 2) / lineHeight));
      }

      const chunkLineCount = Math.min(linesThatFit, maximumLines - lineOffset);
      const rowHeight = Math.max(dense ? 20 : 23, chunkLineCount * lineHeight + TABLE_CELL_PADDING_Y * 2);
      let x = PAGE_MARGIN;

      for (const logicalIndex of visualIndices) {
        const width = widths[logicalIndex];
        const cellY = activeSurface.cursorY;
        activeSurface.context.fillStyle = rowIndex % 2 === 0 ? rgb(WHITE) : rgb(GREEN_FAINT);
        activeSurface.context.fillRect(x, cellY, width, rowHeight);

        if (lineOffset === 0 && percentColumns[logicalIndex]) {
          const numericValue = Number((row[logicalIndex] || "").replace(/[^\d.-]/g, ""));
          if (Number.isFinite(numericValue) && numericValue > 0) {
            const barWidth = (width - 4) * clamp(numericValue / 100, 0, 1);
            activeSurface.context.fillStyle = rgb(GREEN, 0.1);
            activeSurface.context.fillRect(rtl ? x + width - 2 - barWidth : x + 2, cellY + 2, barWidth, rowHeight - 4);
          }
        }

        activeSurface.context.strokeStyle = rgb(BORDER);
        activeSurface.context.lineWidth = 0.55;
        activeSurface.context.strokeRect(x, cellY, width, rowHeight);

        const raw = row[logicalIndex] || "—";
        const numeric = valueLooksNumeric(raw);
        const align: TextAlign = numeric ? "right" : rtl ? "right" : "left";
        const textX = align === "right" ? x + width - TABLE_CELL_PADDING_X : x + TABLE_CELL_PADDING_X;
        const lines = wrappedCells[logicalIndex].slice(lineOffset, lineOffset + chunkLineCount);
        if (lines.length > 0) {
          const totalTextHeight = (lines.length - 1) * lineHeight;
          const baseline = cellY + (rowHeight - totalTextHeight) / 2 + fontSize * 0.36;
          setCanvasFont(activeSurface.context, fontSize, numeric ? 600 : 430);
          drawTextLines(activeSurface.context, lines, textX, baseline, lineHeight, align, rtl ? "rtl" : "ltr", TEXT);
        }
        x += width;
      }

      activeSurface.cursorY += rowHeight;
      lineOffset += chunkLineCount;
      if (lineOffset < maximumLines) {
        activeSurface = requestNewPage();
        drawSectionAndHeader(true);
      }
    }
  });

  activeSurface.cursorY += 12;
  return activeSurface;
};

const renderMinimalHeader = (
  surface: PageSurface,
  spec: ReportPdfSpec,
  pageWidth: number,
  rtl: boolean,
  labels: LocaleLabels,
) => {
  const { context, firstPage } = surface;
  const title = normalizeValue(spec.title) || titleFromFilename(spec.filename);
  const rangeLabel = normalizeValue(spec.rangeLabel) || labels.allRecords;
  const titleAlign: TextAlign = rtl ? "right" : "left";
  const titleX = rtl ? pageWidth - PAGE_MARGIN : PAGE_MARGIN;
  const secondaryAlign: TextAlign = rtl ? "left" : "right";
  const secondaryX = rtl ? PAGE_MARGIN : pageWidth - PAGE_MARGIN;

  if (firstPage) {
    setCanvasFont(context, 7.2, 800);
    drawTextLines(context, [BRAND.toUpperCase()], titleX, 22, 9, titleAlign, rtl ? "rtl" : "ltr", GREEN_DARK);
    setCanvasFont(context, 7.2, 600);
    drawTextLines(context, wrapText(context, rangeLabel, pageWidth * 0.34, 1), secondaryX, 22, 9, secondaryAlign, rtl ? "rtl" : "ltr", MUTED);
    setCanvasFont(context, 17, 760);
    drawTextLines(context, wrapText(context, title, pageWidth * 0.72, 2), titleX, 48, 19, titleAlign, rtl ? "rtl" : "ltr", NAVY);
    context.strokeStyle = rgb(GREEN_DARK);
    context.lineWidth = 1.4;
    context.beginPath();
    context.moveTo(PAGE_MARGIN, 66);
    context.lineTo(pageWidth - PAGE_MARGIN, 66);
    context.stroke();
    surface.cursorY = 78;
    return;
  }

  setCanvasFont(context, 8.2, 720);
  drawTextLines(context, wrapText(context, title, pageWidth * 0.62, 1), titleX, 20, 10, titleAlign, rtl ? "rtl" : "ltr", NAVY);
  setCanvasFont(context, 6.5, 650);
  drawTextLines(context, [BRAND], secondaryX, 20, 8, secondaryAlign, rtl ? "rtl" : "ltr", GREEN_DARK);
  context.strokeStyle = rgb(BORDER);
  context.lineWidth = 0.7;
  context.beginPath();
  context.moveTo(PAGE_MARGIN, 29);
  context.lineTo(pageWidth - PAGE_MARGIN, 29);
  context.stroke();
  surface.cursorY = 39;
};

const renderMinimalContext = (
  surface: PageSurface,
  spec: ReportPdfSpec,
  pageWidth: number,
  rtl: boolean,
  labels: LocaleLabels,
) => {
  if (!surface.firstPage || !spec.context) return;
  const values = ([
    [labels.workspace, normalizeValue(spec.context.workspace)],
    [labels.farm, normalizeValue(spec.context.farm)],
    [labels.season, normalizeValue(spec.context.season)],
    [labels.generated, normalizeValue(spec.context.generatedAt)],
    [labels.generatedBy, normalizeValue(spec.context.generatedBy)],
  ] as Array<[string, string]>).filter(([, value]) => Boolean(value && value !== "—"));
  if (!values.length) return;
  const text = values.map(([label, value]) => `${label}: ${value}`).join("  •  ");
  const availableWidth = pageWidth - PAGE_MARGIN * 2;
  setCanvasFont(surface.context, 6.8, 500);
  const lines = wrapText(surface.context, text, availableWidth, 2);
  const align: TextAlign = rtl ? "right" : "left";
  const x = rtl ? pageWidth - PAGE_MARGIN : PAGE_MARGIN;
  drawTextLines(surface.context, lines, x, surface.cursorY + 8, 10, align, rtl ? "rtl" : "ltr", MUTED);
  surface.cursorY += lines.length * 10 + 10;
};

const renderMinimalSectionTitle = (
  surface: PageSurface,
  title: string | undefined,
  pageWidth: number,
  rtl: boolean,
  continued: boolean,
  labels: LocaleLabels,
) => {
  if (!title) return;
  const display = continued ? `${title} - ${labels.continued}` : title;
  const align: TextAlign = rtl ? "right" : "left";
  const x = rtl ? pageWidth - PAGE_MARGIN : PAGE_MARGIN;
  setCanvasFont(surface.context, 8.2, 750);
  drawTextLines(surface.context, [display], x, surface.cursorY + 12, 10, align, rtl ? "rtl" : "ltr", NAVY);
  surface.context.strokeStyle = rgb(BORDER);
  surface.context.lineWidth = 0.65;
  surface.context.beginPath();
  surface.context.moveTo(PAGE_MARGIN, surface.cursorY + 19);
  surface.context.lineTo(pageWidth - PAGE_MARGIN, surface.cursorY + 19);
  surface.context.stroke();
  surface.cursorY += 27;
};

const renderMinimalMetrics = (
  surface: PageSurface,
  block: MetricsBlock,
  pageWidth: number,
  pageHeight: number,
  rtl: boolean,
  labels: LocaleLabels,
  requestNewPage: () => PageSurface,
) => {
  let activeSurface = surface;
  const availableWidth = pageWidth - PAGE_MARGIN * 2;
  const metricHeight = 43;
  const requiredHeight = (block.title ? 27 : 0) + metricHeight + 8;
  if (activeSurface.cursorY + requiredHeight > pageHeight - PAGE_BOTTOM) activeSurface = requestNewPage();
  renderMinimalSectionTitle(activeSurface, block.title, pageWidth, rtl, false, labels);
  const count = Math.max(block.rows.length, 1);
  const width = availableWidth / count;
  block.rows.forEach(([label, value], index) => {
    const logicalIndex = rtl ? count - index - 1 : index;
    const left = PAGE_MARGIN + logicalIndex * width;
    if (logicalIndex > 0) {
      activeSurface.context.strokeStyle = rgb(BORDER);
      activeSurface.context.lineWidth = 0.6;
      activeSurface.context.beginPath();
      activeSurface.context.moveTo(left, activeSurface.cursorY + 4);
      activeSurface.context.lineTo(left, activeSurface.cursorY + metricHeight - 4);
      activeSurface.context.stroke();
    }
    const align: TextAlign = rtl ? "right" : "left";
    const x = rtl ? left + width - 10 : left + 10;
    setCanvasFont(activeSurface.context, 6.6, 600);
    drawTextLines(activeSurface.context, wrapText(activeSurface.context, label, width - 20, 1), x, activeSurface.cursorY + 14, 8, align, rtl ? "rtl" : "ltr", MUTED);
    setCanvasFont(activeSurface.context, 13.2, 780);
    drawTextLines(activeSurface.context, wrapText(activeSurface.context, value, width - 20, 1), x, activeSurface.cursorY + 35, 14, align, rtl ? "rtl" : "ltr", NAVY);
  });
  activeSurface.cursorY += metricHeight + 10;
  return activeSurface;
};

const renderMinimalTotal = (
  surface: PageSurface,
  block: TotalBlock,
  pageWidth: number,
  pageHeight: number,
  rtl: boolean,
  requestNewPage: () => PageSurface,
) => {
  let activeSurface = surface;
  const height = 42;
  if (activeSurface.cursorY + height > pageHeight - PAGE_BOTTOM) activeSurface = requestNewPage();
  activeSurface.context.strokeStyle = rgb(GREEN_DARK);
  activeSurface.context.lineWidth = 1.2;
  activeSurface.context.beginPath();
  activeSurface.context.moveTo(PAGE_MARGIN, activeSurface.cursorY);
  activeSurface.context.lineTo(pageWidth - PAGE_MARGIN, activeSurface.cursorY);
  activeSurface.context.stroke();
  const labelAlign: TextAlign = rtl ? "right" : "left";
  const valueAlign: TextAlign = rtl ? "left" : "right";
  const labelX = rtl ? pageWidth - PAGE_MARGIN : PAGE_MARGIN;
  const valueX = rtl ? PAGE_MARGIN : pageWidth - PAGE_MARGIN;
  setCanvasFont(activeSurface.context, 7.4, 650);
  drawTextLines(activeSurface.context, [block.label || "Total"], labelX, activeSurface.cursorY + 25, 9, labelAlign, rtl ? "rtl" : "ltr", MUTED);
  setCanvasFont(activeSurface.context, 15, 800);
  drawTextLines(activeSurface.context, [block.value || "—"], valueX, activeSurface.cursorY + 27, 16, valueAlign, rtl ? "rtl" : "ltr", NAVY);
  activeSurface.cursorY += height;
  return activeSurface;
};

const renderMinimalTable = (
  surface: PageSurface,
  block: TableBlock,
  pageWidth: number,
  pageHeight: number,
  rtl: boolean,
  orientation: "portrait" | "landscape",
  labels: LocaleLabels,
  requestNewPage: () => PageSurface,
) => {
  let activeSurface = surface;
  const availableWidth = pageWidth - PAGE_MARGIN * 2;
  const columnCount = block.headers.length;
  const fontSize = orientation === "landscape" ? 6.8 : 7.15;
  const headerFontSize = 6.8;
  const widths = calculateColumnWidths(activeSurface.context, block.headers, block.rows, availableWidth, fontSize);
  const logicalIndices = Array.from({ length: columnCount }, (_, index) => index);
  const visualIndices = rtl ? [...logicalIndices].reverse() : logicalIndices;

  setCanvasFont(activeSurface.context, headerFontSize, 750);
  const headerHeight = Math.max(25, Math.max(...block.headers.map((header, index) => wrapText(activeSurface.context, header, widths[index] - TABLE_CELL_PADDING_X * 2, 2).length)) * (headerFontSize + 2) + 8);

  const drawHeader = () => {
    activeSurface.context.fillStyle = rgb(GREEN_SOFT);
    activeSurface.context.fillRect(PAGE_MARGIN, activeSurface.cursorY, availableWidth, headerHeight);
    let x = PAGE_MARGIN;
    for (const logicalIndex of visualIndices) {
      const width = widths[logicalIndex];
      const values = block.rows.slice(0, 20).map((row) => row[logicalIndex]).filter(Boolean);
      const numeric = values.length > 0 && values.filter(valueLooksNumeric).length / values.length >= 0.7;
      const align: TextAlign = numeric ? "right" : rtl ? "right" : "left";
      const textX = align === "right" ? x + width - TABLE_CELL_PADDING_X : x + TABLE_CELL_PADDING_X;
      setCanvasFont(activeSurface.context, headerFontSize, 750);
      const lines = wrapText(activeSurface.context, block.headers[logicalIndex], width - TABLE_CELL_PADDING_X * 2, 2);
      const totalTextHeight = (lines.length - 1) * (headerFontSize + 2);
      const baseline = activeSurface.cursorY + (headerHeight - totalTextHeight) / 2 + headerFontSize * 0.36;
      drawTextLines(activeSurface.context, lines, textX, baseline, headerFontSize + 2, align, rtl ? "rtl" : "ltr", NAVY);
      x += width;
    }
    activeSurface.context.strokeStyle = rgb(GREEN_DARK);
    activeSurface.context.lineWidth = 0.9;
    activeSurface.context.beginPath();
    activeSurface.context.moveTo(PAGE_MARGIN, activeSurface.cursorY + headerHeight);
    activeSurface.context.lineTo(pageWidth - PAGE_MARGIN, activeSurface.cursorY + headerHeight);
    activeSurface.context.stroke();
    activeSurface.cursorY += headerHeight;
  };

  const drawSectionAndHeader = (continued: boolean) => {
    renderMinimalSectionTitle(activeSurface, block.title, pageWidth, rtl, continued, labels);
    drawHeader();
  };

  const requiredTop = (block.title ? 27 : 0) + headerHeight + 24;
  if (activeSurface.cursorY + requiredTop > pageHeight - PAGE_BOTTOM) activeSurface = requestNewPage();
  drawSectionAndHeader(false);

  if (!block.rows.length) {
    setCanvasFont(activeSurface.context, 8.2, 600);
    drawTextLines(activeSurface.context, [labels.noRecords], rtl ? pageWidth - PAGE_MARGIN : PAGE_MARGIN, activeSurface.cursorY + 24, 10, rtl ? "right" : "left", rtl ? "rtl" : "ltr", MUTED);
    activeSurface.cursorY += 38;
    return activeSurface;
  }

  block.rows.forEach((row, rowIndex) => {
    setCanvasFont(activeSurface.context, fontSize, 400);
    const wrapped = block.headers.map((_, columnIndex) => wrapText(activeSurface.context, row[columnIndex] || "—", widths[columnIndex] - TABLE_CELL_PADDING_X * 2));
    const maximumLines = Math.max(...wrapped.map((lines) => lines.length));
    const lineHeight = fontSize + 2.1;
    let lineOffset = 0;

    while (lineOffset < maximumLines) {
      let availableHeight = pageHeight - PAGE_BOTTOM - activeSurface.cursorY;
      let linesThatFit = Math.floor((availableHeight - 8) / lineHeight);
      if (linesThatFit < 1) {
        activeSurface = requestNewPage();
        drawSectionAndHeader(true);
        availableHeight = pageHeight - PAGE_BOTTOM - activeSurface.cursorY;
        linesThatFit = Math.max(1, Math.floor((availableHeight - 8) / lineHeight));
      }
      const chunkLineCount = Math.min(linesThatFit, maximumLines - lineOffset);
      const rowHeight = Math.max(20, chunkLineCount * lineHeight + 8);
      if (rowIndex % 2 === 1) {
        activeSurface.context.fillStyle = rgb(GREEN_FAINT);
        activeSurface.context.fillRect(PAGE_MARGIN, activeSurface.cursorY, availableWidth, rowHeight);
      }
      let x = PAGE_MARGIN;
      for (const logicalIndex of visualIndices) {
        const width = widths[logicalIndex];
        const raw = row[logicalIndex] || "—";
        const numeric = valueLooksNumeric(raw);
        const align: TextAlign = numeric ? "right" : rtl ? "right" : "left";
        const textX = align === "right" ? x + width - TABLE_CELL_PADDING_X : x + TABLE_CELL_PADDING_X;
        const lines = wrapped[logicalIndex].slice(lineOffset, lineOffset + chunkLineCount);
        if (lines.length) {
          const totalTextHeight = (lines.length - 1) * lineHeight;
          const baseline = activeSurface.cursorY + (rowHeight - totalTextHeight) / 2 + fontSize * 0.36;
          setCanvasFont(activeSurface.context, fontSize, numeric ? 620 : 420);
          drawTextLines(activeSurface.context, lines, textX, baseline, lineHeight, align, rtl ? "rtl" : "ltr", TEXT);
        }
        x += width;
      }
      activeSurface.context.strokeStyle = rgb(BORDER);
      activeSurface.context.lineWidth = 0.45;
      activeSurface.context.beginPath();
      activeSurface.context.moveTo(PAGE_MARGIN, activeSurface.cursorY + rowHeight);
      activeSurface.context.lineTo(pageWidth - PAGE_MARGIN, activeSurface.cursorY + rowHeight);
      activeSurface.context.stroke();
      activeSurface.cursorY += rowHeight;
      lineOffset += chunkLineCount;
      if (lineOffset < maximumLines) {
        activeSurface = requestNewPage();
        drawSectionAndHeader(true);
      }
    }
  });
  activeSurface.cursorY += 12;
  return activeSurface;
};

export async function createReportPdf(spec: ReportPdfSpec): Promise<ArrayBuffer> {
  if (typeof document === "undefined") throw new Error("Report PDF generation requires a browser environment.");
  await ensureReportFont();

  const { jsPDF } = await import("jspdf");
  const orientation = spec.orientation ?? "landscape";
  const rtl = spec.direction === "rtl" || /^(ar|ur)(-|$)/i.test(spec.language ?? "");
  const locale = resolveLocale(spec.language);
  const labels = localeLabels[locale];
  const blocks = parseBlocks(spec.rows, labels);
  const doc = new jsPDF({ orientation, unit: "pt", format: "a4", compress: true, putOnlyUsedFonts: true });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let pageIndex = 0;

  const minimal = spec.variant === "minimal";
  const buildSurface = (firstPage: boolean) => {
    const { canvas, context } = createPageCanvas(pageWidth, pageHeight);
    const surface: PageSurface = { canvas, context, cursorY: 0, firstPage };
    if (minimal) {
      renderMinimalHeader(surface, spec, pageWidth, rtl, labels);
      renderMinimalContext(surface, spec, pageWidth, rtl, labels);
    } else {
      renderHeader(surface, spec, pageWidth, rtl, labels);
      renderContextCards(surface, spec, pageWidth, rtl, labels, orientation);
    }
    return surface;
  };

  let surface = buildSurface(true);

  const commitSurface = () => {
    if (pageIndex > 0) doc.addPage();
    const imageData = surface.canvas.toDataURL("image/jpeg", 0.94);
    doc.addImage(imageData, "JPEG", 0, 0, pageWidth, pageHeight, undefined, "FAST");
    surface.canvas.width = 1;
    surface.canvas.height = 1;
    pageIndex += 1;
  };

  const requestNewPage = () => {
    commitSurface();
    surface = buildSurface(false);
    return surface;
  };

  for (const block of blocks) {
    if (minimal) {
      if (block.kind === "metrics") surface = renderMinimalMetrics(surface, block, pageWidth, pageHeight, rtl, labels, requestNewPage);
      else if (block.kind === "total") surface = renderMinimalTotal(surface, block, pageWidth, pageHeight, rtl, requestNewPage);
      else surface = renderMinimalTable(surface, block, pageWidth, pageHeight, rtl, orientation, labels, requestNewPage);
    } else if (block.kind === "metrics") surface = renderMetrics(surface, block, pageWidth, pageHeight, rtl, orientation, labels, requestNewPage);
    else if (block.kind === "total") surface = renderTotal(surface, block, pageWidth, pageHeight, rtl, requestNewPage);
    else surface = renderTable(surface, block, pageWidth, pageHeight, rtl, orientation, labels, requestNewPage);
  }

  commitSurface();

  const totalPages = doc.getNumberOfPages();
  for (let pageNumber = 1; pageNumber <= totalPages; pageNumber += 1) {
    doc.setPage(pageNumber);
    doc.setDrawColor(...BORDER);
    doc.setLineWidth(0.5);
    doc.line(PAGE_MARGIN, pageHeight - 23, pageWidth - PAGE_MARGIN, pageHeight - 23);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(...MUTED);
    doc.text(BRAND, PAGE_MARGIN, pageHeight - 10);
    doc.text(`${pageNumber} / ${totalPages}`, pageWidth - PAGE_MARGIN, pageHeight - 10, { align: "right" });
  }

  return doc.output("arraybuffer");
}

export async function exportReportPdf(spec: ReportPdfSpec): Promise<void> {
  const buffer = await createReportPdf(spec);
  const blob = new Blob([buffer], { type: "application/pdf" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = normalizeFilename(spec.filename);
  link.style.display = "none";
  document.body.appendChild(link);
  link.click();
  link.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 1_000);
}

export type { ReportPdfContext, ReportPdfSpec };
