import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";

test("temporary reconciliation debug route is gated and linked from settings", () => {
  const source = readFileSync(new URL("../../web/src/components/AccountingReconciliationDebugView.tsx", import.meta.url), "utf8");
  const helperSource = readFileSync(new URL("../../web/src/lib/reconciliationDebug.ts", import.meta.url), "utf8");
  const appSource = readFileSync(new URL("../../web/src/App.tsx", import.meta.url), "utf8");
  const settingsSource = readFileSync(new URL("../../web/src/pages/admin/Settings.tsx", import.meta.url), "utf8");
  const workspaceSettingsSource = readFileSync(new URL("../../web/src/pages/workspace/Farms.tsx", import.meta.url), "utf8");
  const workspaceAccountsRoute = readFileSync(new URL("../../api/src/routes/workspace-accounts.ts", import.meta.url), "utf8");
  const adminWorkspaceSeasonsRoute = readFileSync(new URL("../../api/src/routes/admin-workspace-seasons.ts", import.meta.url), "utf8");
  assert.ok(helperSource.includes("VITE_APP_ENV"));
  assert.ok(helperSource.includes("VITE_ENABLE_RECONCILIATION_DEBUG"));
  assert.ok(helperSource.includes("hostname.includes(\"muzare-main-dev.onrender.com\")"));
  assert.ok(helperSource.includes("Reconciliation debug panel disabled because VITE_ENABLE_RECONCILIATION_DEBUG is not true and hostname is not recognized as dev."));
  assert.ok(source.includes("mode === \"admin\""));
  assert.ok(source.includes("workspace_user"));
  assert.ok(source.includes("dbBackedSession"));
  assert.ok(source.includes("selected workspace"));
  assert.ok(source.includes("All farms"));
  assert.ok(source.includes("All seasons"));
  assert.ok(source.includes("Account search"));
  assert.ok(source.includes("Matched account"));
  assert.ok(source.includes("select a workspace, farm, season, and account without typing UUIDs manually"));
  assert.ok(source.includes("fetchWorkspaceAccounts"));
  assert.ok(source.includes("fetchAdminWorkspaces"));
  assert.ok(source.includes("fetchAdminWorkspace"));
  assert.ok(source.includes("fetchAdminWorkspaceSeasons"));
  assert.ok(source.includes("fetchAccountingReconciliationTrace"));
  assert.ok(source.includes("queryFn: () => fetchAccountingReconciliationTrace(token!, {"));
  assert.ok(source.includes("JSON.stringify({"));
  assert.ok(source.includes("selectedContext"));
  assert.ok(source.includes("permissionMode"));
  assert.ok(source.includes("permissionPassed"));
  assert.ok(appSource.includes("accounting-reconciliation-debug"));
  assert.ok(appSource.includes("/debug/accounting-reconciliation"));
  assert.ok(settingsSource.includes("Accounting Reconciliation Trace"));
  assert.ok(workspaceSettingsSource.includes("/debug/accounting-reconciliation"));
  assert.ok(workspaceAccountsRoute.includes("/v1/workspace/:workspaceId/accounts"));
  assert.ok(adminWorkspaceSeasonsRoute.includes("/v1/admin/workspaces/:workspaceId/farms/:farmId/seasons"));
  assert.ok(workspaceSettingsSource.includes("Accounting Reconciliation Trace"));
});
